[build]
  command="npm run build"
  publish = "dist/ahorrar/browser"
  ignore="exit 1" 

[[plugins]]
  package="@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"